#! /bin/sh

bspc config border_width        2
bspc config window_gap         7

bspc config normal_border_color  "#34322E"
bspc config focused_border_color "#808D49"
bspc config focus_follows_pointer true

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config top_padding 18
bspc config remove_disabled_monitor true

bspc monitor eDP1 -d     
bspc monitor HDMI1 -d 
bspc monitor VGA1 -d 
bspc monitor DP1 -d 

bspc rule -a Firefox desktop=^1
bspc rule -a Steam desktop=^4
bspc rule -a mpv floating=on
bspc rule -a Skype desktop=^5
bspc rule -a Thunderbird desktop=^5
bspc rule -a bubble floating=on
bspc rule -a URxvtQuake sticky=on floating=on


[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
xfce4-power-manager &
thunar --daemon &
lxpolkit &
compton --config $HOME/.config/compton.conf --backend glx --blur-background -m 0.7 &
pulseaudio --start &
wmname LG3D &
panel &
nm-applet &
pa-applet &
nitrogen --restore &
perl /usr/local/share/xSwipe/xSwipe.pl -m 30 &
sleep 2 && trayer --edge top --align right  --widthtype request --width 30 --height 18 --transparent true --alpha 95 --tint 0x95FFFFFF --distance 420 --distancefrom right &