#!/usr/bin/env bash

. panel_colors

bspc config border_width        1
bspc config window_gap         7

bspc config normal_border_color  "#34322E"
bspc config focused_border_color "#808D49"
bspc config focus_follows_pointer true

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config leaf_monocle		true
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config top_padding 18
bspc config remove_disabled_monitor true

bspc monitor eDP1 -n 1 -d     
bspc monitor VGA1 -n 2 -d 
bspc monitor HDMI1 -n 3 -d 
bspc monitor DP1 -n 4 -d 

bspc rule -a Firefox desktop=^1
bspc rule -a Steam desktop=^4
bspc rule -a mpv floating=on
bspc rule -a Skype desktop=^5
bspc rule -a Thunderbird desktop=^5
bspc rule -a bubble floating=on
bspc rule -a URxvtQuake sticky=on floating=on

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
# /home/murat/.screenlayout/display.sh &
xfce4-power-manager &
thunar --daemon &
lxpolkit &
compton --config $HOME/.config/compton.conf -m 0.8 --blur-kern '7,7,0.000003,0.000102,0.000849,0.001723,0.000849,0.000102,0.000003,0.000102,0.003494,0.029143,0.059106,0.029143,0.003494,0.000102,0.000849,0.029143,0.243117,0.493069,0.243117,0.029143,0.000849,0.001723,0.059106,0.493069,0.493069,0.059106,0.001723,0.000849,0.029143,0.243117,0.493069,0.243117,0.029143,0.000849,0.000102,0.003494,0.029143,0.059106,0.029143,0.003494,0.000102,0.000003,0.000102,0.000849,0.001723,0.000849,0.000102,0.000003' &
pulseaudio --start &
wmname LG3D &
panel2 &
# panel3 &
nm-applet &
pa-applet &
nitrogen --restore &
perl /usr/local/share/xSwipe/xSwipe.pl -m 30 &
sleep 2 && trayer --edge top --align right  --widthtype request --width 30 --height 18 --transparent true --alpha 95 --tint 0x95FFFFFF --distance 420 --distancefrom right &
# sleep 2 && trayer --edge top --align right  --widthtype request --width 30 --height 18 --transparent false --tint 0x$COLOR_05 --distance 420 --distancefrom right &
																															  