#!/usr/bin/env bash

. panel_colors

bspc config border_width        2
bspc config window_gap         0

bspc config normal_border_color  "#34322E"
bspc config focused_border_color "#60b48a"
bspc config focused_sticky_border_color "#34322E"
bspc config focus_follows_pointer true

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config leaf_monocle		true
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config top_padding 18

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false

bspc monitor eDP1 -n 1 -d     
bspc monitor VGA1 -n 2 -d  
bspc monitor HDMI1 -n 3 -d  
bspc monitor DP1 -n 4 -d  

bspc rule -a Firefox desktop=^1
bspc rule -a Steam desktop=^4
bspc rule -a jetbrains-studio desktop=^2
bspc rule -a mpv floating=on
bspc rule -a lxappearance floating=on
bspc rule -a nitrogen floating=on
bspc rule -a lxrandr floating=on
bspc rule -a Skype desktop=^5
bspc rule -a Thunderbird desktop=^5
bspc rule -a bubble floating=on
bspc rule -a ^Preferences floating=on
bspc rule -a bubble floating=on
bspc rule -a URxvtQuake sticky=on floating=on layer=above
bspc rule -a dukto floating=on


#set shell that sxhkd uses to execute commands:
export SXHKD_SHELL=/usr/bin/bash

#start bspwm and sxhkd
sxhkd -f 100 -c /home/$USER/.config/sxhkd/sxhkdrc &

wmname LG3D &
panel2 &
sleep 3 && trayer --edge top --align right  --widthtype request --width 30 --height 18 --transparent true --alpha 115 --tint 0x9534322E --distance 420 --distancefrom right --monitor 1 &