#!/bin/sh

# Figure out current screen size
# SCREENWIDTH=$(xrandr -q | grep Screen | awk '{print $8}')
SCREENHEIGHT=$(bspc query -T -m $(bspc query -M -d focused) | grep -oE "[0-9]{2,6}" | head -n 2 | tail -1)
# SCREENHEIGHT=$(xrandr -q | grep Screen | awk '{print $10}' | sed s/,//)
SCREENWIDTH=$(bspc query -T -m $(bspc query -M -d focused) | grep -oE "[0-9]{2,6}" | head -n 1)

# How close to the screen edges do we begin/end?
EDGEWIDTH=50
DMENUWIDTH=$(($SCREENWIDTH - $(($EDGEWIDTH + $EDGEWIDTH))))

# dmenu X/Y coordinates
XPOS=$EDGEWIDTH
YPOS=$(($(($SCREENHEIGHT / 2)) - 15))

FGSELECT="#A3A6AB"
BGSELECT="#60b48a"
#BGSELECT="#8C9440"
FG="#6F7277"
BG="#34322E"
FONT="-*-stlarch-*-*-*-*-*-*-*-*-*-*-*-*"
HIST="${HOME}/.config/bspwm/history"
xkb-switch -s us;
# echo -e "a\n3|b\n4|c\n5" | rofi -sep '|' -eh 2 -dmenu
# rofi -show run ">" -lines 1 -columns 10 -opacity "95" -width $DMENUWIDTH -bg "#FFFFFF" -fg "#34322E" -hlbg $BGSELECT -hlfg $FGSELECT
dmenu_run -w $DMENUWIDTH -x $XPOS -y $YPOS -fn ${FONT} -nb $BG -nf $FG -sb $BGSELECT -p ">" -dim 0.60 -hist ${HIST}
