#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors
menu='%{F$COLOR_BLUE}%{A:thunar:} %{A}%{A:thunar:}%{A}%{A:firefox:} %{A}%{A:subl3:} %{A}%{A:dropbox:} %{A}%{F-}'
num_mon=$(bspc query -M | wc -l)
pow='%{B$COLOR_STATUS_BG}%{A:bat:}%{F$COLOR_BLUE}%{F-}%{A}%{B-}'
cal='%{B$COLOR_STATUS_BG}%{A:cali:}%{F$COLOR_BLUE} %{F-}%{A}%{B-}'
lswtch='%{B$COLOR_STATUS_BG}%{A:xkb-switch -n:}%{F$COLOR_BLUE}%{F-}%{A}%{B-}'
while read -r line ; do
	case $line in
		TE*)
			# Sensor Output
			temp="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line:2:2} %{B-}%{F-}"
			;;
		R*)
			# tray
			tr="${line#?}"
			;;
		L*)
			# Sensor Output
			lang="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#?} %{B-}%{F-}"
			;;
		S*)
			# clock output
			date="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%{B-}%{F-}"
			;;
		C*)

			clock="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}  ${line#?}%{B-}%{F-}"
			;;
		X*)
			# title X
			wkill="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%{B-}%{F-}"
			;;
		B*)
			#Battery Output
			bat="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#?} %{B-} %{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line:1:50} %{B-}%{F-}"
			;;
		A*)
			apps="${line#?}"
			;;
		Y*)
			ya="${line#?}"
			;;
		V*)
			#vol
			vol="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?} %{B-}%{F-}"
			;;
		E*)
			#vol
			weth="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?} %{B-}%{F-}"
			;;
		W*)
        wm_infos=""
        IFS=':'
        set -- ${line#?}
        while [ $# -gt 0 ] ; do
          item=$1
          name=${item#?}
          desk=" $name "
          case $item in
            O*)
              # focused occupied desktop
              wm_infos="$wm_infos%{F$color_01}%{A:bspc desktop -f $name:}$desk%{A}" ;;
            F*)
              # focused empty desktop
              wm_infos="$wm_infos%{F$color_02}%{A:bspc desktop -f $name:}$desk%{A}" ;;
            U*)
              # focused urgent desktop
              wm_infos="$wm_infos%{F$color_03}%{A:bspc desktop -f $name:}$desk%{A}" ;;
            o*)
              # occupied desktop
              wm_infos="$wm_infos%{F$color_04}%{A:bspc desktop -f $name:}$desk%{A}" ;;
            f*)
              # free desktop
              wm_infos="$wm_infos%{F$color_05}%{A:bspc desktop -f $name:}$desk%{A}" ;;
            u*)
              # urgent desktop
              wm_infos="$wm_infos%{F$color_06}%{A:bspc desktop -f $name:}$desk%{A}" ;;
            m*|M*)
              # monitor seperator
              wm_infos="$wm_infos%{F-}  " ;;
          esac
          shift
        done ;;
	esac
	# printf "%s\n" "%{l}${title}${icon}%{c}${wm_infos}${apps}%{r}${vol}${temp}${pow}${bat}${cal}${sys_infos}"
	printf "%s\n" "%{l}${title}${wkill}${icon}%{c}${wm_infos} ${menu}%{r}${vol}${temp}${pow}${bat}${weth}${ya}${lswtch}${lang}${cal}${date}${clock}${tr}"
done
